### ISSUE TITLE
Packaging: More than just .deb

### ISSUE THREAD

**Issue by coxley** [flan/staticdhcpd#46]
Might I suggest using [fpm](https://github.com/jordansissel/fpm) for creating more than just .deb packages for staticdhcpd? Perhaps rpm, deb, and pacman?

**Comment by flan** [comment]
You absolutely may, and I wish I could say I hadn't forgotten about this the last time I came across it.

The current build scripts are really just for rapid testing until I can get enough feedback from users to check off the feature-list to finally declare 2.0 stable; I'll formalise everything for deployment then. Definitely leaving this ticket open as a reminder, though.

**Comment by coxley** [comment]
Great!

Thought I'd mention because it has saved me tons of pain. :)

**Comment by flan** [comment]
I left this not-formally-addressed for far too long, but `fpm` is now actually mentioned in its own section and has been tested on Fedora.

I'll try to do some periodic testing to make sure it's still functional, but, well, you've seen how little time I've been able to dedicate to non-critical bugs in this project over the years, so non-Debian distros will be one of the first things overlooked when bandwidth is tight.
