### ISSUE TITLE
Publishing project to PIP?

### ISSUE THREAD

**Issue by urosjarc** [flan/staticdhcpd#70]
I can't find this project in pip. @flan pls upload this to pip if this is not done already.

**Comment by jansegre** [comment]
I would benefit from `libpydhcpserver` being on PyPI. That piece of the project is useful to me but it I miss the convenience of being able to just `pip install` it or have it on my `setup.py`.

I hope you really consider publishing it.

Best regards.

**Comment by flan** [comment]
It's on the list of things to do, but I'm still waiting for external feedback on whether some things still work as expected. If you can verify that any of the following are operational, I can (finally, after two years) start making progress on moving it out of RC and finish wrapping things for distribution:

- Postgres
- MySQL
- Oracle

I'm not really a PyPi user, though, so it might take a few days, after getting validation that publication won't just result in a ton of bug reports for untested features, before I'll have time to ensure that whatever is assembled is packaged correctly.

**Comment by jansegre** [comment]
Actually I'm forking `libpydhcpserver.dhcp_types`, because I'm using python 3, and asyncio. I'm still unsure if this will meet my needs, if it does I'll try to merge back my contribution to this project.
