### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by remingtonc** [flan/staticdhcpd#73]
Is IPv6 well supported with staticdhcpd? I know there are some nuances with v4 vs v6 in ISC DHCP server, wondering what staticdhcpd's take on it is.

**Comment by flan** [comment]
I'm afraid that IPv6 isn't currently supported in any form.

I am planning to create an IPv6-focused stream once the common components needed for IPv4 were established, but there are a few outstanding items that I cannot validate myself that have prevented this from happening over the past couple of years.

(DHCPv6 is a very different beast, protocol-wise, from DHCP, but they do share a number of common concepts and a similar-enough workflow)

**Comment by flan** [comment]
Given that I've been working outside of the network-management domain for a while, I'm probably not the right person to build a DHCPv6 server.

I'm updating staticDHCPd to work with Python 3 and merging in some wishlist features, but my focus is on maintenance now, while hoping IPv4 marches towards its end quickly.
