### ISSUE TITLE
Doesn't support python 3 (and doesn't document that)

### ISSUE THREAD

**Issue by howardjones** [flan/staticdhcpd#75]
Build fails with Python 3.5 due to various syntax errors (e.g. old-style print) in libpydhcpserver... 

Also, the README doesn't mention that python 3 isn't supported. It's been 10 years - maybe acknowledge its existence :-)

**Comment by flan** [comment]
I'm finally doing a proper Python 3-native port, in what time I can spare.

It's in the 3.0.x branch and, as of today, it seems to be functional, though there's a long list of features to be tested, outlined near the start of README.md. If this is still relevant to you, please try pulling it and seeing if you can check anything off the list.

Migration-tracking is being handled in issue #89.
