### ISSUE TITLE
adding extentions 

### ISSUE THREAD

**Issue by JOELEJAUNE** [flan/staticdhcpd#78]
hello , 

hope all is good at your side.

i'm working on adding some lines of code that i want to execute whenever the DHCPdiscover message reaches the staticDHCP Server.

any idea that could help me would be appreciated.

thanks & regards

**Comment by flan** [comment]
If you want to react as soon as DISCOVER is received, you'll want to look at filterPacket(): http://static.uguu.ca/projects/staticDHCPd/doc/customisation/scripting.html#filterpacket

Drop a snippet like what's in the example below, with an `if method == "DISCOVER":`-like check, into conf.py and it should work.

**Comment by JOELEJAUNE** [comment]
Good evening sir,

Thanks a lot for your fast reply.
I will start working on this.

Regards


Le mar. 31 juil. 2018 20:18, Neil Tallim <notifications@github.com> a
écrit :
