### ISSUE TITLE
Cannot load mysql.sql on MariaDB 10.3.17

### ISSUE THREAD

**Issue by ryny24** [flan/staticdhcpd#83]
I just did a fresh install twice, but cannot load the mysql.sql file due to the following error:

`user@DHCP-TEST-1:~/staticdhcpd $  mysql -u root -p dhcp < /tmp/mysql.sql 
Enter password: 
ERROR 1064 (42000) at line 4: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' 
    subnet_mask CHAR(15), 
    broadcast_address CHAR(15), 
    ntp_servers CH' at line 5`

It seems I can't install mysql-server anymore on a raspberry pi. I have to use MariaDB.

`~/staticdhcpd` $ mysql -V
mysql  Ver 15.1 Distrib 10.3.17-MariaDB, for debian-linux-gnueabihf (armv7l) using readline `5.2`

The statement in the sql appears to be correct, but I'm no expect. However, it does not create the table.

**Comment by flan** [comment]
Thanks for reporting this!

I just pushed a74a5f48eabfa382ef4a1fd6edef044c811be52a, which should let execution complete.

If this works for you, I would absolutely love to hear about it. Having someone independently verify that MySQL works (and MariaDB is close enough) is the last thing needed before I can finally move this project out of beta status. (...And then migrate it to Python 3, but that's another matter)

**Comment by ryny24** [comment]
Yes, that worked. That was quick. I'm excited to get this working.

I'm going to try to customize it to store the option-82 from cisco switches. Hopefully that is possible lol

**Comment by flan** [comment]
You shouldn't have any trouble trapping packets that have that option set and then doing whatever you want with that data. Most DHCP clients are pretty tolerant of delays on the order of seconds if you have to do a ton of processing there for some reason.

It looks like I've dealt with 82 before: http://static.uguu.ca/projects/staticDHCPd/doc/examples/index.html#working-with-option-82

http://static.uguu.ca/projects/staticDHCPd/doc/customisation/scripting.html#loaddhcppacket is the full function spec, ~~though it looks like there's a formatting issue; I'll try to regen the docs to fix it~~.
