### ISSUE TITLE
Error in the rfc3925_125_decode function

### ISSUE THREAD

**Issue by ancahy** [flan/staticdhcpd#87]
Python returns an error when using the undefined value variable.
On the other hand, the variable l does not seem to be used anywhere in the function code.

https://github.com/flan/staticdhcpd/blob/ba38626b2406501d68363e8fdd37e608bfcb6898/libpydhcpserver/libpydhcpserver/dhcp_types/rfc.py#L70

**Comment by flan** [comment]
I'm not sure how I didn't see this issue come in... over a year ago, but it's fixed in the Python 3 port branch.

The argument should have been `value`, not `l`, but I suspect you corrected that locally already.
