### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by andrew-azarov** [flan/staticdhcpd#90]
It's not available anymore, pages show either domain not available for static.uguu.ca or nothing is available

**Comment by flan** [comment]
Ah, sorry. My old webhost gave me pretty short notice on closing and I didn't migrate this yet.

I'll have it up as soon as DNS and documentation-regen allow.

**Comment by flan** [comment]
It should be back up as soon as the cached not-available (NXDOMAIN) record expires between you and your DNS server. I had an exported backup, so it's from 2.0.0-rc1, but nothing significant has changed between that and the Python3 rework.

Thank you for letting me know that I forgot to do this step.

(And if you're using or testing anything that can be crossed off the todo list on the project's main page, please let me know)
